// Enhanced mock data with more realistic entries and metadata
export const mockEntries = [
  {
    id: "1",
    title: "Finding Balance in Chaos",
    date: "2023-04-15T12:00:00Z",
    content:
      "<p>Today was particularly challenging at work. The project deadline was moved up by two weeks, and the team is feeling the pressure. Despite the chaos, I managed to find moments of calm by taking short breaks and practicing deep breathing.</p><p>I'm noticing that when I consciously make time for these micro-breaks, my productivity actually improves. It's counterintuitive but effective.</p><p>Tomorrow I'll try implementing the Pomodoro technique - 25 minutes of focused work followed by a 5-minute break. I've heard good things about it from colleagues.</p>",
    tags: ["work", "stress-management", "self-care", "productivity"],
    sentiment: "Mixed",
    topics: ["Work Stress", "Coping Strategies", "Productivity"],
    wordCount: 89,
    readTime: 1,
    hasMedia: false,
    hasCode: false,
    location: "Home Office",
    weather: "Rainy",
    mood: 6,
    lastEdited: "2023-04-15T14:30:00Z",
  },
  {
    id: "2",
    title: "Reflections on Personal Growth",
    date: "2023-04-22T15:30:00Z",
    content:
      "<p>Looking back at my journal entries from six months ago, I'm struck by how much my perspective has shifted. The challenges that seemed insurmountable then appear manageable now. I've developed more effective coping mechanisms and a stronger sense of self-awareness.</p><p>The daily meditation practice I started has been transformative. I'm more present in my interactions and less reactive to stress triggers.</p><p>I've also noticed that my language has changed - fewer self-critical statements and more compassionate self-talk. The cognitive behavioral therapy techniques are clearly working.</p><p>Next goal: work on setting clearer boundaries in my professional relationships.</p>",
    tags: ["personal growth", "meditation", "self-awareness", "reflection", "mindfulness"],
    sentiment: "Positive",
    topics: ["Mindfulness", "Progress", "Emotional Intelligence", "Self-Improvement"],
    wordCount: 112,
    readTime: 1,
    hasMedia: false,
    hasCode: false,
    location: "Park",
    weather: "Sunny",
    mood: 8,
    lastEdited: "2023-04-22T16:45:00Z",
  },
  {
    id: "3",
    title: "Navigating Relationship Dynamics",
    date: "2023-05-01T20:15:00Z",
    content:
      "<p>Had a difficult conversation with Alex today about boundaries. It was uncomfortable but necessary. I'm proud of myself for articulating my needs clearly without becoming defensive.</p><p>I noticed that using the 'I feel' statements we discussed in therapy helped keep the conversation productive. There's still work to do, but this feels like progress in our communication patterns.</p><p>One thing I need to work on is not immediately trying to fix things when Alex shares problems. Sometimes listening is all that's needed.</p><p>We've agreed to check in weekly about how we're both feeling, which should help prevent issues from building up unaddressed.</p>",
    tags: ["relationships", "communication", "boundaries", "personal growth"],
    sentiment: "Neutral",
    topics: ["Interpersonal Skills", "Conflict Resolution", "Boundaries", "Active Listening"],
    wordCount: 105,
    readTime: 1,
    hasMedia: false,
    hasCode: false,
    location: "Living Room",
    weather: "Cloudy",
    mood: 6,
    lastEdited: "2023-05-01T22:10:00Z",
  },
  {
    id: "4",
    title: "Creative Breakthrough",
    date: "2023-05-10T18:45:00Z",
    content:
      "<p>After weeks of creative block, I finally had a breakthrough on my project! The solution came to me during my morning walk, when I wasn't actively thinking about the problem.</p><p>This reinforces something I've experienced before: my best ideas often emerge when I step away and give my subconscious mind space to work. I need to remember to build more unstructured thinking time into my creative process.</p><p>I sketched out the initial concept as soon as I got home:</p><img src=\"/placeholder.svg?height=300&width=400\" alt=\"Project Sketch\" /><p>Tomorrow I'll start implementing the first prototype. I'm excited to see how it develops!</p>",
    tags: ["creativity", "problem-solving", "insights", "design", "inspiration"],
    sentiment: "Very Positive",
    topics: ["Creative Process", "Inspiration", "Work Projects", "Design Thinking"],
    wordCount: 98,
    readTime: 1,
    hasMedia: true,
    hasCode: false,
    location: "Coffee Shop",
    weather: "Sunny",
    mood: 9,
    lastEdited: "2023-05-10T20:15:00Z",
  },
  {
    id: "5",
    title: "Health and Wellness Check-in",
    date: "2023-05-15T21:00:00Z",
    content:
      "<p>I've been consistent with my new exercise routine for three weeks now. The first week was a struggle, but it's becoming easier to maintain the habit. I'm noticing improvements in my energy levels and sleep quality.</p><p>My goal for the next month is to add more variety to my workouts and focus on nutrition. I tend to neglect meal planning when work gets busy, which leads to poor food choices.</p><p>Current stats:</p><ul><li>Weight: 165 lbs (down 3 lbs)</li><li>Resting heart rate: 68 bpm (down 4 bpm)</li><li>Average sleep: 7.2 hours (up 0.5 hours)</li><li>Weekly workouts: 4</li></ul><p>I'm proud of the progress so far, but need to stay consistent.</p>",
    tags: ["health", "exercise", "habits", "goals", "fitness", "nutrition"],
    sentiment: "Positive",
    topics: ["Physical Health", "Habit Formation", "Goal Setting", "Fitness"],
    wordCount: 120,
    readTime: 1,
    hasMedia: false,
    hasCode: false,
    location: "Home Gym",
    weather: "Clear",
    mood: 7,
    lastEdited: "2023-05-15T22:30:00Z",
  },
  {
    id: "6",
    title: "Financial Planning Thoughts",
    date: "2023-05-20T14:30:00Z",
    content:
      "<p>Reviewed my budget and financial goals today. I'm making progress on building my emergency fund, but I'm still not saving as much for retirement as I'd like.</p><p>I identified several areas where I can reduce spending without significantly impacting my quality of life. The key will be consistency and avoiding impulse purchases.</p><p>Current financial breakdown:</p><pre>Monthly Income: $5,200\nEssential Expenses: $2,800\nNon-essential: $1,200\nSavings: $1,200\n\nEmergency Fund: $8,400 / $15,000 goal\nRetirement: Contributing 8% (target: 15%)</pre><p>Next steps: Cut streaming subscriptions I rarely use and reduce dining out to twice per week.</p>",
    tags: ["finances", "budgeting", "goals", "planning", "saving"],
    sentiment: "Neutral",
    topics: ["Financial Planning", "Budgeting", "Long-term Goals", "Saving"],
    wordCount: 110,
    readTime: 1,
    hasMedia: false,
    hasCode: true,
    location: "Home Office",
    weather: "Rainy",
    mood: 6,
    lastEdited: "2023-05-20T16:00:00Z",
  },
  {
    id: "7",
    title: "Gratitude Reflection",
    date: "2023-05-25T22:15:00Z",
    content:
      "<p>Today I'm feeling particularly grateful for my support network. When I was overwhelmed with the project deadline, Sarah stepped in to help without being asked. These small acts of kindness make such a difference.</p><p>I'm also appreciative of my health, my comfortable home, and the opportunity to do work that challenges me intellectually. Even on difficult days, there's so much to be thankful for.</p><p>Three specific things I'm grateful for today:</p><ol><li>The phone call with mom that brightened my morning</li><li>The perfect cup of coffee from the new shop down the street</li><li>Finding time to read for pleasure before bed last night</li></ol><p>I want to make this gratitude practice a daily habit.</p>",
    tags: ["gratitude", "relationships", "perspective", "mindfulness", "habits"],
    sentiment: "Very Positive",
    topics: ["Support Systems", "Appreciation", "Positive Outlook", "Mental Health"],
    wordCount: 125,
    readTime: 1,
    hasMedia: false,
    hasCode: false,
    location: "Bedroom",
    weather: "Clear",
    mood: 9,
    lastEdited: "2023-05-25T23:00:00Z",
  },
  {
    id: "8",
    title: "Learning JavaScript Promises",
    date: "2023-06-02T19:20:00Z",
    content:
      "<p>I've been struggling with asynchronous JavaScript, so today I dedicated some time to really understanding Promises. The concept finally clicked!</p><p>Here's a simple example I worked through:</p><pre><code class=\"language-javascript\">// Creating a simple promise\nconst myPromise = new Promise((resolve, reject) => {\n  // Simulating an async operation\n  setTimeout(() => {\n    const success = true;\n    \n    if (success) {\n      resolve('Operation completed successfully!');\n    } else {\n      reject('Operation failed!');\n    }\n  }, 1000);\n});\n\n// Using the promise\nmyPromise\n  .then(result => {\n    console.log(result); // 'Operation completed successfully!'\n  })\n  .catch(error => {\n    console.error(error);\n  });\n</code></pre><p>The key insight was understanding that Promises represent a value that might not be available yet. This mental model makes async/await much clearer too.</p><p>Tomorrow I'll practice by refactoring some of my callback-based code to use Promises and async/await.</p>",
    tags: ["programming", "javascript", "learning", "web development", "coding"],
    sentiment: "Positive",
    topics: ["Learning", "Web Development", "JavaScript", "Problem Solving"],
    wordCount: 150,
    readTime: 2,
    hasMedia: false,
    hasCode: true,
    location: "Home Office",
    weather: "Rainy",
    mood: 7,
    lastEdited: "2023-06-02T20:45:00Z",
  },
  {
    id: "9",
    title: "Weekend Hiking Adventure",
    date: "2023-06-10T18:30:00Z",
    content:
      '<p>Went on an amazing hike at Mount Rainier today! The weather was perfect - clear skies with a gentle breeze. The wildflowers are in full bloom, creating a stunning carpet of colors across the meadows.</p><p>We took the Skyline Trail, which was challenging but absolutely worth it for the views. Total distance: 5.5 miles with 1,700 feet of elevation gain.</p><img src="/placeholder.svg?height=400&width=600" alt="Mount Rainier Hiking View" /><p>Wildlife spotted:</p><ul><li>Two marmots sunning themselves on rocks</li><li>A family of deer grazing in a meadow</li><li>Various birds including what I think was a hawk</li></ul><p>My legs are tired but my spirit is refreshed. Nature has such a powerful way of putting life\'s problems into perspective.</p><p>Next weekend: exploring the Olympic Peninsula if the weather holds!</p>',
    tags: ["hiking", "nature", "outdoors", "adventure", "self-care", "photography"],
    sentiment: "Very Positive",
    topics: ["Outdoor Activities", "Nature", "Adventure", "Photography"],
    wordCount: 140,
    readTime: 1,
    hasMedia: true,
    hasCode: false,
    location: "Mount Rainier",
    weather: "Sunny",
    mood: 10,
    lastEdited: "2023-06-10T20:00:00Z",
  },
  {
    id: "10",
    title: "Reflecting on Career Goals",
    date: "2023-06-15T21:45:00Z",
    content:
      "<p>Had my mid-year review today, which prompted some deep thinking about my career trajectory. While I'm performing well in my current role, I'm not sure it's aligned with my long-term goals.</p><p>I created a simple matrix to evaluate potential next steps:</p><table><thead><tr><th>Option</th><th>Growth Potential</th><th>Work-Life Balance</th><th>Compensation</th><th>Alignment with Interests</th></tr></thead><tbody><tr><td>Current Path</td><td>Medium</td><td>Good</td><td>Medium</td><td>Medium</td></tr><tr><td>Management Track</td><td>High</td><td>Poor</td><td>High</td><td>Low</td></tr><tr><td>Specialization</td><td>Medium</td><td>Medium</td><td>High</td><td>High</td></tr><tr><td>Career Change</td><td>High</td><td>Unknown</td><td>Low initially</td><td>High</td></tr></tbody></table><p>Looking at this objectively, specializing in UX design seems most aligned with my values and interests. I should explore certification options and networking opportunities in that field.</p><p>Action items:</p><ol><li>Research UX certification programs</li><li>Reach out to Sarah and Michael who work in UX</li><li>Look for small projects where I can practice UX skills</li></ol>",
    tags: ["career", "planning", "goals", "professional development", "decision making"],
    sentiment: "Neutral",
    topics: ["Career Planning", "Professional Development", "Decision Making", "Goal Setting"],
    wordCount: 180,
    readTime: 2,
    hasMedia: false,
    hasCode: false,
    location: "Home Office",
    weather: "Cloudy",
    mood: 6,
    lastEdited: "2023-06-15T23:00:00Z",
  },
  {
    id: "11",
    title: "Mindfulness Meditation Progress",
    date: "2023-06-20T06:15:00Z",
    content:
      "<p>Completed my 30th consecutive day of morning meditation today! What started as a 5-minute daily practice has gradually extended to 15 minutes, and I'm noticing significant benefits:</p><ul><li>Reduced anxiety, especially in high-pressure work situations</li><li>Improved focus during meetings and deep work sessions</li><li>Better emotional regulation when faced with frustrations</li><li>More present in conversations with friends and family</li></ul><p>The Headspace app has been helpful, but I'm also exploring unguided meditation now that I'm more comfortable with the practice.</p><p>One challenge remains: maintaining consistency on weekends when my routine is different. Setting a specific time rather than tying it to my workday routine might help.</p><p>I'm proud of building this habit and curious to see how the benefits develop over longer periods.</p>",
    tags: ["meditation", "mindfulness", "habits", "mental health", "personal growth"],
    sentiment: "Positive",
    topics: ["Mindfulness", "Habit Formation", "Mental Health", "Self-Improvement"],
    wordCount: 135,
    readTime: 1,
    hasMedia: false,
    hasCode: false,
    location: "Living Room",
    weather: "Clear",
    mood: 8,
    lastEdited: "2023-06-20T07:00:00Z",
  },
  {
    id: "12",
    title: "Recipe Experiment: Homemade Pasta",
    date: "2023-06-25T19:30:00Z",
    content:
      '<p>Attempted making homemade pasta from scratch today! The process was more involved than I expected but incredibly satisfying.</p><p>Recipe:</p><pre>Ingredients:\n- 2 cups all-purpose flour\n- 3 large eggs\n- 1/2 teaspoon salt\n- 1 tablespoon olive oil\n- Extra flour for dusting</pre><p>The dough came together beautifully, though kneading it for 10 minutes was quite the arm workout! Rolling it out without a pasta machine was challenging - next time I\'ll invest in proper equipment.</p><img src="/placeholder.svg?height=350&width=500" alt="Homemade Fettuccine" /><p>I served it with a simple brown butter and sage sauce, which complemented the fresh pasta perfectly. The texture was noticeably different from dried pasta - more tender and with a pleasant chew.</p><p>Lessons for next time:</p><ol><li>Let the dough rest longer (at least 30 minutes)</li><li>Roll it even thinner</li><li>Cut the noodles more consistently</li><li>Consider a pasta machine!</li></ol><p>Despite the imperfections, there\'s something deeply satisfying about making such a fundamental food from scratch. Will definitely try again!</p>',
    tags: ["cooking", "food", "recipes", "hobbies", "creativity"],
    sentiment: "Positive",
    topics: ["Cooking", "Creativity", "Learning", "Hobbies"],
    wordCount: 190,
    readTime: 2,
    hasMedia: true,
    hasCode: false,
    location: "Kitchen",
    weather: "Clear",
    mood: 8,
    lastEdited: "2023-06-25T21:00:00Z",
  },
  {
    id: "13",
    title: "Book Reflection: Atomic Habits",
    date: "2023-07-01T22:00:00Z",
    content:
      '<p>Just finished reading "Atomic Habits" by James Clear, and I\'m blown away by how practical and insightful it is. The core message about focusing on systems rather than goals resonates deeply with me.</p><p>Key takeaways:</p><ol><li>Tiny changes compound over time - 1% better every day leads to significant improvement</li><li>Focus on identity rather than outcomes ("I am a runner" vs. "I want to run a marathon")</li><li>Make good habits obvious, attractive, easy, and satisfying</li><li>Make bad habits invisible, unattractive, difficult, and unsatisfying</li><li>Environment design is more important than willpower</li></ol><p>I\'m going to apply these principles to three areas of my life:</p><p>1. <strong>Reading habit:</strong> Place a book on my pillow each morning so I read before bed instead of scrolling on my phone</p><p>2. <strong>Exercise:</strong> Sleep in workout clothes and place running shoes by the door to make morning workouts easier</p><p>3. <strong>Healthy eating:</strong> Prep vegetables right after grocery shopping and place them at eye level in the fridge</p><p>The idea that really stuck with me is: "You do not rise to the level of your goals. You fall to the level of your systems."</p>',
    tags: ["books", "habits", "personal development", "productivity", "self-improvement"],
    sentiment: "Positive",
    topics: ["Reading", "Habit Formation", "Personal Development", "Productivity"],
    wordCount: 200,
    readTime: 2,
    hasMedia: false,
    hasCode: false,
    location: "Living Room",
    weather: "Rainy",
    mood: 8,
    lastEdited: "2023-07-01T23:15:00Z",
  },
  {
    id: "14",
    title: "Anxiety and Coping Strategies",
    date: "2023-07-05T23:30:00Z",
    content:
      '<p>Experienced a significant anxiety spike today during the team presentation. My heart was racing, palms sweating, and I felt that familiar tightness in my chest. While I made it through, it was uncomfortable and affected my performance.</p><p>Triggers I identified:</p><ul><li>Lack of preparation time due to last-minute changes</li><li>Large audience including senior leadership</li><li>Technical difficulties right before starting</li><li>Poor sleep the night before</li></ul><p>Coping strategies I used:</p><ol><li>Box breathing (4 counts in, 4 hold, 4 out, 4 hold)</li><li>Grounding technique: naming 5 things I could see, 4 I could touch, etc.</li><li>Reframing thoughts from "This is a disaster" to "This is challenging but manageable"</li></ol><p>What worked well was the breathing technique and having water nearby. What didn\'t work was trying to ignore the anxiety - acknowledging it actually helped more.</p><p>For future high-stress situations, I\'ll:</p><ul><li>Prepare further in advance when possible</li><li>Practice the presentation multiple times</li><li>Get better sleep the night before</li><li>Arrive early to test technology</li><li>Continue using breathing techniques</li></ul><p>I\'m trying to view this as data, not failure. Each anxiety experience teaches me more about my triggers and effective coping strategies.</p>',
    tags: ["anxiety", "mental health", "coping strategies", "work stress", "self-care"],
    sentiment: "Negative",
    topics: ["Anxiety", "Coping Strategies", "Work Stress", "Mental Health"],
    wordCount: 220,
    readTime: 2,
    hasMedia: false,
    hasCode: false,
    location: "Bedroom",
    weather: "Stormy",
    mood: 4,
    lastEdited: "2023-07-06T00:15:00Z",
  },
  {
    id: "15",
    title: "Planning My Garden Redesign",
    date: "2023-07-10T17:45:00Z",
    content:
      '<p>Spent the afternoon sketching plans for the backyard garden redesign. I want to create a space that balances beauty with functionality - somewhere to grow vegetables but also relax and entertain.</p><p>Current layout:</p><pre>+---------------------+\n|      Lawn          |\n|                     |\n+--------+--+--------+\n|        |  |        |\n| Flower |  | Flower |\n|  Bed   |  |  Bed   |\n+--------+--+--------+\n|       Patio        |\n|                    |\n+--------------------+</pre><p>Proposed new layout:</p><pre>+---------------------+\n| Vegetable Garden   |\n|                    |\n+--------+--+--------+\n|        |  |        |\n| Herb   |  | Flower |\n| Garden |  | Garden |\n+--------+--+--------+\n|    Seating Area    |\n|                    |\n+--------------------+</pre><p>Plants I want to include:</p><ul><li>Vegetables: tomatoes, cucumbers, zucchini, bell peppers</li><li>Herbs: basil, rosemary, thyme, mint (in containers to prevent spreading)</li><li>Flowers: lavender, echinacea, black-eyed susans, butterfly bush</li></ul><p>I\'m particularly excited about adding a small water feature and creating designated pollinator-friendly areas. The goal is to have the initial work done by end of August so plants can establish before fall.</p><img src="/placeholder.svg?height=300&width=500" alt="Garden Design Sketch" /><p>Next steps: pricing materials and creating a project timeline.</p>',
    tags: ["gardening", "design", "hobbies", "planning", "nature"],
    sentiment: "Positive",
    topics: ["Gardening", "Design", "Planning", "Hobbies"],
    wordCount: 230,
    readTime: 2,
    hasMedia: true,
    hasCode: true,
    location: "Backyard",
    weather: "Sunny",
    mood: 8,
    lastEdited: "2023-07-10T19:00:00Z",
  },
]

export const mockTags = [
  { id: "1", name: "work", count: 15 },
  { id: "2", name: "relationships", count: 12 },
  { id: "3", name: "health", count: 10 },
  { id: "4", name: "creativity", count: 8 },
  { id: "5", name: "finances", count: 6 },
  { id: "6", name: "gratitude", count: 14 },
  { id: "7", name: "stress-management", count: 9 },
  { id: "8", name: "goals", count: 11 },
  { id: "9", name: "self-care", count: 13 },
  { id: "10", name: "meditation", count: 7 },
  { id: "11", name: "personal growth", count: 16 },
  { id: "12", name: "productivity", count: 9 },
  { id: "13", name: "mindfulness", count: 11 },
  { id: "14", name: "learning", count: 8 },
  { id: "15", name: "books", count: 5 },
  { id: "16", name: "cooking", count: 6 },
  { id: "17", name: "exercise", count: 9 },
  { id: "18", name: "nature", count: 7 },
  { id: "19", name: "programming", count: 4 },
  { id: "20", name: "anxiety", count: 5 },
]

// Enhanced emotion data for visualizations
export const mockEmotions = {
  labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
  datasets: [
    {
      label: "Joy",
      data: [65, 59, 80, 81, 56, 75, 82],
      color: "#10b981", // emerald-500
    },
    {
      label: "Sadness",
      data: [28, 48, 40, 19, 26, 17, 15],
      color: "#0ea5e9", // sky-500
    },
    {
      label: "Anxiety",
      data: [45, 39, 30, 53, 36, 25, 42],
      color: "#8b5cf6", // violet-500
    },
    {
      label: "Contentment",
      data: [60, 55, 65, 70, 60, 80, 75],
      color: "#14b8a6", // teal-500
    },
    {
      label: "Anger",
      data: [20, 35, 15, 10, 25, 18, 12],
      color: "#ef4444", // red-500
    },
  ],
  // Daily mood data for the past 30 days
  dailyMood: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (29 - i) * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    value: Math.floor(Math.random() * 5) + 5, // Random value between 5-10
  })),
}

// Mock user data
export const mockUser = {
  id: "user1",
  name: "Jamie Doe",
  email: "jamie@example.com",
  avatar: "/placeholder.svg?height=128&width=128",
  joinDate: "2023-01-15T00:00:00Z",
  preferences: {
    theme: "system",
    language: "en",
    reminderTime: "20:00",
    reminderFrequency: "daily",
    defaultPrivacy: "private",
  },
  stats: {
    totalEntries: 142,
    streakCurrent: 16,
    streakLongest: 21,
    tagsUsed: 35,
    wordsWritten: 28450,
    averageWordsPerEntry: 200,
    entriesThisMonth: 12,
    entriesLastMonth: 18,
  },
  subscription: {
    plan: "premium",
    renewalDate: "2023-12-15T00:00:00Z",
    features: ["unlimited entries", "advanced analytics", "API access", "priority support"],
  },
}

// Mock reminders data
export const mockReminders = [
  {
    id: "1",
    title: "Evening Journal",
    time: "20:00",
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    active: true,
    message: "Time to reflect on your day!",
    lastTriggered: "2023-07-09T20:00:00Z",
  },
  {
    id: "2",
    title: "Gratitude Practice",
    time: "08:00",
    days: ["monday", "wednesday", "friday"],
    active: true,
    message: "What are three things you're grateful for today?",
    lastTriggered: "2023-07-10T08:00:00Z",
  },
  {
    id: "3",
    title: "Weekly Review",
    time: "18:00",
    days: ["sunday"],
    active: true,
    message: "Time for your weekly reflection. How did the week go?",
    lastTriggered: "2023-07-09T18:00:00Z",
  },
  {
    id: "4",
    title: "Mood Check-in",
    time: "12:00",
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    active: false,
    message: "How are you feeling right now? Take a moment to check in.",
    lastTriggered: "2023-07-07T12:00:00Z",
  },
]

// Mock prompts for journaling inspiration
export const mockPrompts = [
  {
    id: "1",
    text: "What are three things you're grateful for today?",
    category: "gratitude",
    usageCount: 24,
  },
  {
    id: "2",
    text: "Describe a challenge you're facing and three potential solutions.",
    category: "problem-solving",
    usageCount: 18,
  },
  {
    id: "3",
    text: "What's something you're looking forward to, and why does it excite you?",
    category: "positivity",
    usageCount: 15,
  },
  {
    id: "4",
    text: "Reflect on a recent interaction that affected you emotionally. What did you learn?",
    category: "relationships",
    usageCount: 21,
  },
  {
    id: "5",
    text: "What's one small step you can take today toward a long-term goal?",
    category: "goals",
    usageCount: 19,
  },
  {
    id: "6",
    text: "Describe a moment when you felt proud of yourself recently.",
    category: "self-reflection",
    usageCount: 16,
  },
  {
    id: "7",
    text: "What boundaries do you need to establish or reinforce in your life?",
    category: "personal-growth",
    usageCount: 14,
  },
  {
    id: "8",
    text: "If you could give advice to your younger self, what would it be?",
    category: "reflection",
    usageCount: 22,
  },
  {
    id: "9",
    text: "What's something you've been avoiding, and what's one small step to address it?",
    category: "productivity",
    usageCount: 17,
  },
  {
    id: "10",
    text: "Describe your ideal day. What elements can you incorporate into your life now?",
    category: "lifestyle",
    usageCount: 20,
  },
]

// Mock AI insights for the dashboard
export const mockInsights = [
  {
    id: "1",
    text: "Your entries show a positive trend in emotional well-being over the past month. Keep up the good work!",
    type: "positive",
    date: "2023-07-10T10:00:00Z",
    topics: ["emotional well-being", "trends", "progress"],
    relatedEntries: ["2", "7", "11"],
  },
  {
    id: "2",
    text: "You've mentioned 'work stress' in 7 entries this month. Consider exploring stress management techniques.",
    type: "suggestion",
    date: "2023-07-09T10:00:00Z",
    topics: ["work stress", "stress management", "mental health"],
    relatedEntries: ["1", "3", "14"],
  },
  {
    id: "3",
    text: "Your language patterns indicate increased self-compassion compared to last month.",
    type: "positive",
    date: "2023-07-08T10:00:00Z",
    topics: ["self-compassion", "language patterns", "personal growth"],
    relatedEntries: ["2", "11", "13"],
  },
  {
    id: "4",
    text: "You tend to journal more productively in the morning. Consider making it part of your morning routine.",
    type: "suggestion",
    date: "2023-07-07T10:00:00Z",
    topics: ["productivity", "routines", "habits"],
    relatedEntries: ["5", "11", "13"],
  },
  {
    id: "5",
    text: "Your entries mentioning 'family' are consistently associated with positive emotions.",
    type: "positive",
    date: "2023-07-06T10:00:00Z",
    topics: ["family", "relationships", "positive emotions"],
    relatedEntries: ["7", "9", "12"],
  },
  {
    id: "6",
    text: "There's a correlation between your outdoor activities and improved mood scores.",
    type: "insight",
    date: "2023-07-05T10:00:00Z",
    topics: ["outdoor activities", "mood", "mental health"],
    relatedEntries: ["4", "9", "15"],
  },
  {
    id: "7",
    text: "Your financial entries show increasing organization and planning. This structured approach is helping reduce money-related stress.",
    type: "positive",
    date: "2023-07-04T10:00:00Z",
    topics: ["finances", "organization", "stress reduction"],
    relatedEntries: ["6"],
  },
  {
    id: "8",
    text: "Consider setting specific, measurable goals for your meditation practice to build on your current progress.",
    type: "suggestion",
    date: "2023-07-03T10:00:00Z",
    topics: ["meditation", "goal setting", "habits"],
    relatedEntries: ["2", "11"],
  },
]

// Mock topic data for topic modeling
export const mockTopics = [
  {
    id: "1",
    name: "Work and Career",
    keywords: ["work", "project", "deadline", "team", "productivity", "career", "professional"],
    entries: ["1", "4", "10", "14"],
    sentiment: "mixed",
    frequency: {
      Jan: 5,
      Feb: 7,
      Mar: 4,
      Apr: 8,
      May: 6,
      Jun: 9,
      Jul: 4,
    },
  },
  {
    id: "2",
    name: "Personal Growth",
    keywords: ["growth", "learning", "progress", "goals", "improvement", "development", "habits"],
    entries: ["2", "5", "11", "13"],
    sentiment: "positive",
    frequency: {
      Jan: 3,
      Feb: 5,
      Mar: 8,
      Apr: 10,
      May: 12,
      Jun: 9,
      Jul: 11,
    },
  },
  {
    id: "3",
    name: "Health and Wellness",
    keywords: ["health", "exercise", "sleep", "energy", "nutrition", "fitness", "wellness"],
    entries: ["5", "11"],
    sentiment: "positive",
    frequency: {
      Jan: 6,
      Feb: 4,
      Mar: 7,
      Apr: 5,
      May: 8,
      Jun: 10,
      Jul: 7,
    },
  },
  {
    id: "4",
    name: "Relationships",
    keywords: ["relationships", "communication", "boundaries", "support", "connection", "family", "friends"],
    entries: ["3", "7", "14"],
    sentiment: "mixed",
    frequency: {
      Jan: 8,
      Feb: 6,
      Mar: 5,
      Apr: 7,
      May: 4,
      Jun: 6,
      Jul: 5,
    },
  },
  {
    id: "5",
    name: "Creativity and Hobbies",
    keywords: ["creativity", "hobbies", "projects", "art", "writing", "cooking", "gardening"],
    entries: ["4", "12", "15"],
    sentiment: "positive",
    frequency: {
      Jan: 4,
      Feb: 3,
      Mar: 6,
      Apr: 5,
      May: 7,
      Jun: 8,
      Jul: 9,
    },
  },
  {
    id: "6",
    name: "Finances",
    keywords: ["finances", "budget", "saving", "spending", "investment", "money", "financial"],
    entries: ["6"],
    sentiment: "neutral",
    frequency: {
      Jan: 2,
      Feb: 3,
      Mar: 1,
      Apr: 4,
      May: 2,
      Jun: 3,
      Jul: 1,
    },
  },
  {
    id: "7",
    name: "Mental Health",
    keywords: ["anxiety", "stress", "coping", "mental health", "emotions", "therapy", "self-care"],
    entries: ["1", "3", "11", "14"],
    sentiment: "mixed",
    frequency: {
      Jan: 7,
      Feb: 9,
      Mar: 6,
      Apr: 5,
      May: 8,
      Jun: 7,
      Jul: 10,
    },
  },
  {
    id: "8",
    name: "Learning and Education",
    keywords: ["learning", "education", "skills", "knowledge", "books", "reading", "courses"],
    entries: ["8", "13"],
    sentiment: "positive",
    frequency: {
      Jan: 3,
      Feb: 4,
      Mar: 5,
      Apr: 3,
      May: 6,
      Jun: 4,
      Jul: 5,
    },
  },
]

// Mock word frequency data for word cloud
export const mockWordFrequency = [
  { text: "work", value: 45 },
  { text: "feel", value: 38 },
  { text: "time", value: 35 },
  { text: "today", value: 32 },
  { text: "good", value: 30 },
  { text: "meditation", value: 28 },
  { text: "better", value: 25 },
  { text: "progress", value: 24 },
  { text: "goals", value: 22 },
  { text: "health", value: 21 },
  { text: "stress", value: 20 },
  { text: "grateful", value: 19 },
  { text: "family", value: 18 },
  { text: "focus", value: 17 },
  { text: "challenge", value: 16 },
  { text: "learning", value: 15 },
  { text: "happy", value: 14 },
  { text: "exercise", value: 13 },
  { text: "sleep", value: 12 },
  { text: "reading", value: 11 },
  { text: "project", value: 10 },
  { text: "anxiety", value: 9 },
  { text: "creative", value: 8 },
  { text: "morning", value: 7 },
  { text: "routine", value: 6 },
  { text: "mindful", value: 5 },
  { text: "practice", value: 4 },
  { text: "journal", value: 3 },
  { text: "write", value: 2 },
  { text: "reflect", value: 1 },
]

